# Generated by Django 3.1.3 on 2020-11-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='free',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='persona',
            name='work',
            field=models.IntegerField(default=0),
        ),
    ]
